---

- hosts: Web
  sudo: yes

  tasks:
   - name: stop wildfly service
     service: name=wildfly state=stopped

  roles:
     - { role: wildfly }
     - { role: jenkins, version: latest, install_dir: '/opt/wildfly/standalone/deployments' }

  tasks:
   - name: start wildfly service
     service: name=wildfly state=started

