---

- hosts: Web
  sudo: yes
  serial: 1
  vars:
    new_jenkins_version: "{{ new_version |default('1.609.1') }}"

  tasks:
   - name: Arret service Wildfly
     service: name=wildfly state=stopped

  roles:
   - { role: jenkins, version: '{{ new_jenkins_version }}', install_dir: '/opt/wildfly/standalone/deployments/' }

  tasks:
   - name: demarrage service wildfly
     service: name=wildfly state=started

   - name: affichage message
     debug: msg="web mis a jour en version {{ new_jenkins_version }} "
