---


- include: openjdk.yml version=openjdk-7-jdk

- name: Create wildfly user
  user: name={{ wildfly_user }} group=root home=/opt/wildfly state=present

- name: Download wildfly tar file
  get_url: dest=/tmp url={{ wildfly_url}} owner={{ wildfly_user }}  force=no 
  register: wildflydwl

- name: Extract wildfly
  command: tar -xzf /tmp/wildfly-servlet-9.0.2.Final.tar.gz --strip-components=1 -C {{ wildfly_dir }}
  when: wildflydwl.changed

- name: set rights
  command: chown -R {{ wildfly_user }} {{ wildfly_dir }}
  when: wildflydwl.changed

- name: Copy wildfly configuration
  template: src=wildfly.conf dest=/etc/default/wildfly owner=root group=root mode=0644

- name: Service creation
  copy: src=wildfly dest=/etc/init.d/wildfly owner=root group=root mode=0755

- name: enabled wildfly service
  service: name=wildfly state=stopped enabled=yes
